apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather
      name: backend
  template:
    metadata:
      labels:
        app: weather
        name: backend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: backend
          image: 195216432339.dkr.ecr.eu-west-3.amazonaws.com/weatherapp/backend:v1.2 
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: development
            - name: DEBUG
              value: "True"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "5000"
            - name: WEATHER_API_KEY
              value: "demo_key"
            - name: LOG_LEVEL
              value: info
