apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend
  labels:
    name:  frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather
      name: frontend
  template:
    metadata:
      labels:
        app: weather
        name:  frontend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - image:  195216432339.dkr.ecr.eu-west-3.amazonaws.com/weatherapp/frontend:latest
        name:  frontend
        resources:
          requests:
            cpu: "20m"
            memory: "55Mi"
        env:
        - name:  NODE_ENV
          value:  development     
        - name:  PORT
          value: "3000"
        - name: BACKEND_URL 
          value: "http://backend:5000"
        - name: LOG_LEVEL
          value: info
        ports:
        - containerPort:  3000