apiVersion: v1
kind: Service
metadata:
  name:  frontend
spec:
  selector:
    name:  frontend
    app: weather
  type:  LoadBalancer
  ports:
  - port:  3000
    targetPort:  3000
  
---

apiVersion: v1
kind: Service
metadata:
  name:  backend
spec:
  selector:
    name:  backend
    app : weather
  type:  ClusterIP
  ports:
  - port:  5000
    targetPort:  5000